// index.js
#!/usr/bin/env node
const yargs = require('yargs');

function run(name, verbose) {
  if (verbose) console.error(`[DEBUG] name=${name}`);
  console.log(`Hello, ${name}!`);
}

const argv = yargs
  .usage('$0 [name]')
  .option( {'verbose', type: 'boolean', describe: 'Verbose output' })
  .default('_', ['World'])
  .help()
  .argv;

run(argv._[0] || 'World', argv.verbose);
